import { type Project } from '../types'

export const PROJECTS: Project[] = [
  {
    id: crypto.randomUUID(),
    name: 'Portflio',
    technologies: ['React', 'TypeScript'],
    mainTechnology: 'React',
    description: 'lorem ipsum lapà',
    language: 'TypeScript',
  },
  {
    id: crypto.randomUUID(),
    name: 'CafeShop',
    technologies: ['Node', 'Express'],
    mainTechnology: 'Vue',
    description: 'lorem ipsum lapà',
    language: 'TypeScript',
  },
  {
    id: crypto.randomUUID(),
    name: 'CafeShop',
    technologies: ['Node', 'Express'],
    mainTechnology: 'Node',
    description: 'lorem ipsum lapà',
    language: 'TypeScript',
  },
  {
    id: crypto.randomUUID(),
    name: 'Videocrypto.randomUUID()tore',
    technologies: ['Vue', 'TypeScript'],
    mainTechnology: 'React',
    description: 'lorem ipsum lapà',
    language: 'JavaScript',
  },
  {
    id: crypto.randomUUID(),
    name: 'Videocrypto.randomUUID()tore',
    technologies: ['Vue', 'TypeScript'],
    mainTechnology: 'Vue',
    description: 'lorem ipsum lapà',
    language: 'JavaScript',
  },
  {
    id: crypto.randomUUID(),
    name: 'Node',
    technologies: ['Vue', 'TypeScript'],
    mainTechnology: 'Node',
    description: 'lorem ipsum lapà',
    language: 'JavaScript',
  },
  {
    id: crypto.randomUUID(),
    name: 'Videocrypto.randomUUID()tore',
    technologies: ['Vue', 'TypeScript'],
    mainTechnology: 'React',
    description: 'lorem ipsum lapà',
    language: 'Python',
  },
  {
    id: crypto.randomUUID(),
    name: 'Videocrypto.randomUUID()tore',
    technologies: ['Vue', 'TypeScript'],
    mainTechnology: 'React',
    description: 'lorem ipsum lapà',
    language: 'Python',
  },
  {
    id: crypto.randomUUID(),
    name: 'Videocrypto.randomUUID()tore',
    technologies: ['Vue', 'TypeScript'],
    mainTechnology: 'React',
    description: 'lorem ipsum lapà',
    language: 'PHP',
  },
  {
    id: crypto.randomUUID(),
    name: 'Who will win',
    technologies: ['Python', 'Pandas'],
    mainTechnology: 'React',
    description: 'lorem ipsum lapà',
    language: 'PHP',
  },
]
