import { type Project } from '../types'

export const PROJECTS: Project[] = [
  {
    id: crypto.randomUUID(),
    name: 'Portflio',
    technologies: ['Tailwind', 'useContext'],
    mainTechnology: 'React',
    description: 'lorem ipsum lapà',
    language: 'TypeScript',
  },
  {
    id: crypto.randomUUID(),
    name: 'Videoteca',
    technologies: ['Pinia', 'Tailwind'],
    mainTechnology: 'Vue',
    description: 'lorem ipsum lapà',
    language: 'TypeScript',
  },
  {
    id: crypto.randomUUID(),
    name: 'CafeShop',
    technologies: ['MySQL', 'Express'],
    mainTechnology: 'Node',
    description: 'lorem ipsum lapà',
    language: 'TypeScript',
  },
  {
    id: crypto.randomUUID(),
    name: 'Todo',
    technologies: ['CSS', 'Redux'],
    mainTechnology: 'React',
    description: 'lorem ipsum lapà',
    language: 'JavaScript',
  },
  {
    id: crypto.randomUUID(),
    name: 'Vue simple',
    technologies: ['Vue', 'TypeScript'],
    mainTechnology: 'Vue',
    description: 'lorem ipsum lapà',
    language: 'JavaScript',
  },
  {
    id: crypto.randomUUID(),
    name: 'Maximun',
    technologies: ['Expres', 'Mongo'],
    mainTechnology: 'Node',
    description: 'lorem ipsum lapà',
    language: 'JavaScript',
  },
  {
    id: crypto.randomUUID(),
    name: 'Who will wim',
    technologies: ['Pandas', 'Scrapy'],
    mainTechnology: 'React',
    description: 'lorem ipsum lapà',
    language: 'Python',
  },
  {
    id: crypto.randomUUID(),
    name: 'Api simple python',
    technologies: ['Vue', 'TypeScript'],
    mainTechnology: 'React',
    description: 'lorem ipsum lapà',
    language: 'Python',
  },
  {
    id: crypto.randomUUID(),
    name: 'Videocrypto.randomUUID()tore',
    technologies: ['Vue', 'TypeScript'],
    mainTechnology: 'React',
    description: 'lorem ipsum lapà',
    language: 'PHP',
  },
  {
    id: crypto.randomUUID(),
    name: 'Who will win',
    technologies: ['Python', 'Pandas'],
    mainTechnology: 'React',
    description: 'lorem ipsum lapà',
    language: 'PHP',
  },
]
